name: Generate Contribution Snake
on:
  schedule:
    - cron: "0 0 * * *" # 每天自动更新一次
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: l73989712-a11y
          outputs: |
            dist/snake.svg?palette=github-dark
      
      - name: Push Snake to Repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          directory: dist
